// <auto-generated />
namespace _31CodeFirst.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addconnectTeachertoSubject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addconnectTeachertoSubject));
        
        string IMigrationMetadata.Id
        {
            get { return "201808211358096_add connect Teacher-to-Subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
